server:
  port: 7071

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: admin-service
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RBUSERNAME}
    password: ${RBPASS}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HRPAdminDB
    username: ${PGUSERNAME}
    password: ${PGPASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
rabbitmq:
  exchange:
    direct: "exchange-direct"
    fanout: "exchange-fanout"
    topic : "exchange-topic"
  key:
    register:
      admin: "binding-key-register-admin"
      manager: "binding-key-register-manager"
      employee: "binding-key-register-employee"
  queue:
    register:
      admin: "queue-register-admin"
      manager: "queue-register-manager"
      employee: "queue-register-employee"
