server:
  port: 7070

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: admin-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HRPAdminDB
    username: postgres
    password: asd123asd # ortam degiskeni yapialacak
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

dropbox:
  token: "sl.BdVgQLBmb7QWzBEOxYJu1uKNRGL3qE7VP_01ck0p0ZM9G4lu1JYPh9xgtIbZnO44OGs2dy0ltgME42Fnmo85wY8gSpW0Sd4hu2rA8HH-9X5YEUAKK8gMqu1TZ4t2CsZGTxvc60sryXxJ"