server:
  port: 7070

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RBUSERNAME}
    password: ${RBPASS}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HRPAuthDB
    username: ${PGUSERNAME}
    password: ${PGPASS}
  jpa:
    hibernate:
      ddl-auto: update

rabbitmq:
  exchange:
    direct: "exchange-direct"
    fanout: "exchange-fanout"
    topic : "exchange-topic"
  key:
    register:
      admin: "binding-key-register-admin"
      manager: "binding-key-register-manager"
      employee: "binding-key-register-employee"
  queue:
    register:
      admin: "queue-register-admin"
      manager: "queue-register-manager"
      employee: "queue-register-employee"