server:
  port: 7071

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HRPAuthDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update