server:
  port: 7073

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: company-service
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27000
      username: "user"
      password: "root"
      database: HRPCompanyDB