server:
  port: 7072

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: company-manager-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HRPCompanyManagerDB
    username: postgres
    password: 4628 # ortam degiskeni yapialacak
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true